speech:
  name: zipformer
  path: "aichat.components.stt.zipformer:ZipformerSTT"
  config:
    sample_rate: 16000
    model_dir: "models/zipformer"
    device: "cpu"

emotion:
  name: deepface
  path: "aichat.components.video.deepface:DeepFaceVideoAnalyzer"
  config:
    sample_rate: 5 # frame per second
    decay_rate: 7

llm:
  name: qwen2.5
  path: "aichat.components.llm.transformer:Transformer"
  config:
    model: unsloth/Qwen2.5-0.5B-unsloth-bnb-4bit
    temperature: 0.7
    gpu_utilization: 0.5
    lora_path: models/qwen2.5-lora
    lora_name: main
    lora_rank: 8

voice:
  name: kokoro
  path: "aichat.components.tts.kokoro:KokoroTTS"
  config:
    device: cpu

lc:
  target_ms: 3000
  upper_limit: 1.30
  lower_limit: 0.80



avatars:
  faces:
    - name: julia
      path: /static/assets/avatars/julia.glb
      gender: F
      mode: neutral
    - name: david
      path: /static/assets/avatars/julia.glb
      gender: M
      mode: neutral
  voices:
    - name: af_bella
      path: /static/assets/voices/af_bella.bin
    - name: am_fenrir
      path: /static/assets/voices/af_bella.bin

      