from typing import Protocol, AsyncGenerator, Dict, Any

class TTS(Protocol):    
    def synthesize(self, text: str) -> AsyncGenerator[tuple[bytes, Dict], Any]: ...
    
    def configure(*args, **kwargs): ...
