from typing import Protocol, AsyncGenerator

class TTS(Protocol):    
    def synthesize(self, text: str) -> AsyncGenerator[bytes, None]: ...
    
    async def warmup(self, text: str): ...
    
    def sampling_rate(self) -> int: ...