from typing import Protocol, Literal, AsyncGenerator

class LLM(Protocol):
    @classmethod
    def configure(cls, *args, **kwargs): ...
    
    def generate(self, text: str) -> AsyncGenerator[str, None]: ...
    
    async def warmup(self, text: str): ...
